---
- name: "Imprimir variable ansible_hostname"
  debug:
    msg: "El hostname es {{ ansible_hostname }}"

- name: Inicio de archivo HTML
  copy:
    dest: /tmp/senha_general.html
    content: |
            <html>
               <head>
                  <title>Resumen de despliegue</title>
                  <meta charset="UTF-8">
                  <meta name="viewport" content="width=device-width, initial-scale=1">
                  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
                  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
                  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
                  <div class="jumbotron jumbotron-fluid" style="background-color:white;padding-top: 0px;padding-bottom: 0px">
                    <div class="container">
                       <img src="https://drive.google.com/uc?id=1QqaTGiBl0y9HeAlZ_iqyLP21y_YdBbay&export=download" class="img-responsive">
                    </div>
                  </div>
               </head>
               <body>
                 <div class="container">
  ignore_errors: True

- name: Creación de tabla Generales
  blockinfile:
    path: /tmp/senha_general.html
    marker: ""
    block: |
            <!-- Tabla de contenido -->
                         <table class="table table-striped">
                              <tr>
                                <th style="color:white; background-color:#3C79C2; text-align:center; font-weight: bold" colspan="2">DATOS GENERALES</th>
                              </tr>
                            <tr>
                               <td>Número de ticket:  </td>
                               <td> {{ numero_de_ticket }} </td>
                            </tr>
                            <tr>
                               <td>Nombre del solicitante:  </td>
                               <td> {{ nombre_solicitante }} </td>
                            </tr>
                            <tr>
                               <td>Correo del solicitante:  </td>
                               <td> {{ correo_solicitante }} </td>
                            </tr>
                            <tr>
                               <td>Centro de datos:  </td>
                               <!-- <td> {{ centro_datos_sat }} </td> -->
                               <td> {{ trans_centro_datos_sat }} </td>
                            </tr>
                            <tr>
                               <td>Tipo de ambiente:  </td>
                               <td> {{ selector_de_ambiente }} </td>
                            </tr>
                            <tr>
                               <td>Fecha de creación de servicio:  </td>
                               <td> {{ fecha_inicio_proceso }} </td>
                            </tr>
                            <tr>
                               <td>Fecha de término de despliegue:  </td>
                               <td> {{ detarea.end[:19] }} </td>
                            </tr>
                         </table>
  ignore_errors: True

- name: Final de archivo HTML
  blockinfile:
    path: /tmp/senha_general.html
    marker: ""
    block: |
        <!-- final de archivo-->
                </div>
              </body>
          </html>
  ignore_errors: True

- set_fact:
    nombre_archivo: "/tmp/{{ numero_de_ticket }}-{{ nombre_catalogo | regex_replace('\\.') | regex_replace(' ') }}_{{ fecha_inicio_proceso | regex_replace('-') | regex_replace(':') | regex_replace(' ')}}"
  ignore_errors: True

- name: Renombrado de archivo HTML
  copy:
    src: /tmp/senha_general.html
    dest: "{{ nombre_archivo }}.html"
  ignore_errors: True

- name: Envio de correo electrónico con los datos del despliegue
  import_tasks: enviar_correo.yml
  vars:
    #general_correo_de: "senha.notificacion@gmail.com"
    #general_correo_para: "{{ correo_solicitante }}"
    #general_correo_concopia: "{{ lista_correo_electronico }}"
    #general_correo_asunto: "Folio {{ numero_de_ticket }} - Despliegue completado - {{ nombre_catalogo }}"
    correo_cuerpo: |
                   <br/>Datos generales del despliegue con el folio <b>{{ numero_de_ticket }}</b>.-
                   <br/>
                   <ul>
                   <li>Item desplegado: <b>{{ nombre_catalogo }}</b></li>
                   <li>Solicitante / Correo:  <b>{{ nombre_solicitante }}</b> / <b>{{ estructura_ambiente.senha_generales.correo_solicitante }}</b></li>
                   <li>Aplicación / Versión:  <b>{{ nombre_aplicacion }}</b> / <b>{{ estructura_ambiente.senha_generales.version_proyecto }}</b></li>
                   <li>Ambiente: <b>{{ selector_de_ambiente }}</b></li>
                   <li>Centro de Datos: <b>{{ trans_centro_datos_sat }}</b></li>
                   <li>Estado de despliegue: <b>Exitoso</b></li>
                   </ul>
                   <br/>
                   <br/>Documentos anexos.-
                   <ul>
                   <li>Documento detalle de elementos desplegados en formato HTML: <b>{{ nombre_archivo | regex_replace('/tmp/') }}.html</b></li>
                   </ul>
                   <br/>
                   <br/>Nota importante de usuarios.-
                   <ul>
    correo_adjuntos: "{{ nombre_archivo }}.html"
    tipo_evento_notificacion: "resultado_Ok"
  ignore_errors: True
...
